### ISSUE TITLE
Asset detail partials don't render in Asset#show

### ISSUE THREAD

**Issue by Dascr32** [richin13/tidylabs#3]
The warranty, specs and others are missing. Probably caused by removing turbolinks. 

QR code rendering had the same issue in IdentificationCode#show, it was caused by the 
```'turbolinks:load``` (see 926eb599aabb309b506c4528e3d0da439a80c00e). 

However, it seems that the ```Asset``` coffee file was modified in 0600a39783f3928172be735ef03fb8e621e58264 to prevent this from happening, but for some reason the partials are not rendering. 

![image](https://user-images.githubusercontent.com/10204977/26861254-e0734394-4aff-11e7-9a98-79f22efdae27.png)

**Comment by Dascr32** [comment]
Never mind, just finished reading f0521213a997eee55f7940766b9f77ec255aa3a3. For the record, asset categories don't show any details by default :grin:. My bad.

**Comment by richin13** [comment]
Probably related with f0521213a997eee55f7940766b9f77ec255aa3a3

Take a look at https://github.com/richin13/tydilabs/commit/f0521213a997eee55f7940766b9f77ec255aa3a3#diff-1acd2e7e27a227829d5d14a91c863bb6

If you go through the code and resolve that this is still an issue please add more steps on how to reproduce this.

Marking as invalid for now.

**Comment by richin13** [comment]
Oh, great! I forgot to mention https://github.com/richin13/tydilabs/commit/f0521213a997eee55f7940766b9f77ec255aa3a3 earlier today
