### ISSUE TITLE
TypeError: `nil can't be coerced into Integer` when adding new areas

### ISSUE THREAD

**Issue by richin13** [richin13/tidylabs#4]
# Problem

Every time a new area is added the areas listing page fails to render because of a `TypeError` due to the property `assets` in `@area` is set to null. The bug was [probably] introduced in 63d7a4a30269f789199f344e5995512ec7eb154d 
Running `rake tydilabs:reset_caches:area_assets` fixes the issue

# Steps to reproduce

- Add a new area
- Inmediatly after the area creation, the application will fail to show the newly-created area
- The Areas#index will also fail

**Comment by Dascr32** [comment]
Thanks for pointing this out. As you said, in 63d7a4a30269f789199f344e5995512ec7eb154d I introduced counter caches to improve app performance in the long run. 

I forgot to add a default value for the column that stores the asset count, so when a new area was created the column was always ```nil```. Now in 68f98dbb5b7cfa625097d78fcbfb1a0cc3e8bc29 the column have a default value of ```0``` and everything works as expected.

**Comment by richin13** [comment]
Great! Closing
